checkpoint_path: "sft_checkpoints/qwen3-14b/v1/checkpoint-592"
translations_path: "translate/results/qwen3-14b_translations.csv"
max_new_tokens: 128
batch_size: 16
use_batches: true
shots: [0, 1]
fuzzy: [null, true]
do_tokenizer_check: true
do_translation: false

# tokenizer settings
# before translation make sure that they match to what you had during tokenizer check in training
# padding_side at training a decoder only model should be right, but at generation it should be left
remove_special_tokens_at_encoding: False
remove_special_tokens_at_decoding: False
add_bos_token: true
bos_token: null
add_eos_token: false
eos_token: null
padding_side: left
pad_token: null
use_fast_tokenizer: true