model: "mistral-medium-latest"
max_tokens: 30
temperature: 0.7
system_prompt_0shot: "You are a helpful assistant that translates English to French. Output only the french sentence no explanations."
system_prompt_few_shot: "You are a helpful assistant that translates English to French. Output only the french sentence no explanations. Use the examples provided."
translations_dir: "translate/translations/"
translations_file: "mistral_medium_translations.csv"
